version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Run build
          command: |
            ./gradlew assemble
      - android/save-gradle-cache
      - android/save-build-cache


  unit_test:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Run unit tests
          command: |
            ./gradlew testDevDebugUnitTest
      - android/restore-gradle-cache
      - android/restore-build-cache

workflows:
  build-orb:
    jobs:
      - android/build

  build-mine:
    jobs:
      - build
      - unit_test:
          requires:
            - build
